//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioItems.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventarioEntities : DbContext
    {
        public InventarioEntities()
            : base("name=InventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Brands> TBL_Brands { get; set; }
        public virtual DbSet<TBL_Companies> TBL_Companies { get; set; }
        public virtual DbSet<TBL_Computer_Types> TBL_Computer_Types { get; set; }
        public virtual DbSet<TBL_Computers> TBL_Computers { get; set; }
        public virtual DbSet<TBL_Employees> TBL_Employees { get; set; }
        public virtual DbSet<TBL_History> TBL_History { get; set; }
        public virtual DbSet<TBL_Monitors> TBL_Monitors { get; set; }
        public virtual DbSet<TBL_Status> TBL_Status { get; set; }
        public virtual DbSet<TBL_Telephones> TBL_Telephones { get; set; }
    }
}
