//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioItems.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_History
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int Item_Type { get; set; }
        public int Device_ID { get; set; }
        public Nullable<System.DateTime> Acquisition_Date { get; set; }
    
        public virtual TBL_Computers TBL_Computers { get; set; }
        public virtual TBL_Employees TBL_Employees { get; set; }
        public virtual TBL_Monitors TBL_Monitors { get; set; }
        public virtual TBL_Telephones TBL_Telephones { get; set; }
    }
}
