//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioItems.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Employees()
        {
            this.TBL_Computers = new HashSet<TBL_Computers>();
            this.TBL_History = new HashSet<TBL_History>();
            this.TBL_Monitors = new HashSet<TBL_Monitors>();
            this.TBL_Telephones = new HashSet<TBL_Telephones>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Employee_Status { get; set; }
    
        public virtual TBL_Companies TBL_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Computers> TBL_Computers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_History> TBL_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Monitors> TBL_Monitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Telephones> TBL_Telephones { get; set; }
    }
}
